### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by vidister** [port-zero/website#10]
- Add a page for Jobs (There we can also can reuse the Post-Scheme we already know from the Team- or References-Page)
- Maybe add an "and you?" Section to the bottom of the Team-Page linking to the Jobs-Page.

**Comment by vilwarin** [comment]
we are looking for people to support Thomas and Jonas team @hellerve 
not urgently though. this gives us the time to pick great candidates that really match the team and tasks :) therefore we decided to put the opening online on a long term basis

**Comment by hellerve** [comment]
I updated the job openings now. It would be great if @meredithmichael could translate it whenever she finds time to do so. Then we can deploy them! 🎉
